repo:
  - '*'

action:
  - any: ['.github/*']

public:
  - any: ['public/*']

source:
  - any: ['src/**/*']

asset:
  - any: ['src/assets/*']

component:
  - any: ['src/components/*']

data:
  - any: ['src/data/*']

font:
  - any: ['src/fonts/*']

util:
  - any: ['arc/utils/*']
