name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
      - name: Build and deploy app
        run: yarn && yarn run deploy
