name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy app
        run: | 
         git config --local user.name 'Github Action'
         git config --local user.email action@github.com
         yarn && yarn run deploy
