name: deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build app
        run: yarn && yarn run build
      - uses: crazy-max/ghaction-github-pages@v2
        if: success()
        with:
         target_branch: gh-pages
         build_dir: public
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
